/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetConnectorTasksResponse Connector tasks fetched.
type GetConnectorTasksResponse struct {
	// List of tasks for the connector.
	Tasks []GetConnectorTasksResponseTasks `json:"tasks,omitempty"`
}

// NewGetConnectorTasksResponse instantiates a new GetConnectorTasksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConnectorTasksResponse() *GetConnectorTasksResponse {
	this := GetConnectorTasksResponse{}
	return &this
}

// NewGetConnectorTasksResponseWithDefaults instantiates a new GetConnectorTasksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConnectorTasksResponseWithDefaults() *GetConnectorTasksResponse {
	this := GetConnectorTasksResponse{}
	return &this
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *GetConnectorTasksResponse) GetTasks() []GetConnectorTasksResponseTasks {
	if o == nil || o.Tasks == nil {
		var ret []GetConnectorTasksResponseTasks
		return ret
	}
	return o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorTasksResponse) GetTasksOk() ([]GetConnectorTasksResponseTasks, bool) {
	if o == nil || o.Tasks == nil {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *GetConnectorTasksResponse) HasTasks() bool {
	if o != nil && o.Tasks != nil {
		return true
	}

	return false
}

// SetTasks gets a reference to the given []GetConnectorTasksResponseTasks and assigns it to the Tasks field.
func (o *GetConnectorTasksResponse) SetTasks(v []GetConnectorTasksResponseTasks) {
	o.Tasks = v
}

func (o GetConnectorTasksResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Tasks != nil {
		toSerialize["tasks"] = o.Tasks
	}
	return json.Marshal(toSerialize)
}

type NullableGetConnectorTasksResponse struct {
	value *GetConnectorTasksResponse
	isSet bool
}

func (v NullableGetConnectorTasksResponse) Get() *GetConnectorTasksResponse {
	return v.value
}

func (v *NullableGetConnectorTasksResponse) Set(val *GetConnectorTasksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConnectorTasksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConnectorTasksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConnectorTasksResponse(val *GetConnectorTasksResponse) *NullableGetConnectorTasksResponse {
	return &NullableGetConnectorTasksResponse{value: val, isSet: true}
}

func (v NullableGetConnectorTasksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConnectorTasksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


