/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse2003Connector Connector status.
type InlineResponse2003Connector struct {
	// State of the connector.
	State *string `json:"state,omitempty"`
	// ID of the worker running the connector.
	WorkerId *string `json:"worker_id,omitempty"`
}

// NewInlineResponse2003Connector instantiates a new InlineResponse2003Connector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2003Connector() *InlineResponse2003Connector {
	this := InlineResponse2003Connector{}
	return &this
}

// NewInlineResponse2003ConnectorWithDefaults instantiates a new InlineResponse2003Connector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2003ConnectorWithDefaults() *InlineResponse2003Connector {
	this := InlineResponse2003Connector{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *InlineResponse2003Connector) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003Connector) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *InlineResponse2003Connector) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *InlineResponse2003Connector) SetState(v string) {
	o.State = &v
}

// GetWorkerId returns the WorkerId field value if set, zero value otherwise.
func (o *InlineResponse2003Connector) GetWorkerId() string {
	if o == nil || o.WorkerId == nil {
		var ret string
		return ret
	}
	return *o.WorkerId
}

// GetWorkerIdOk returns a tuple with the WorkerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2003Connector) GetWorkerIdOk() (*string, bool) {
	if o == nil || o.WorkerId == nil {
		return nil, false
	}
	return o.WorkerId, true
}

// HasWorkerId returns a boolean if a field has been set.
func (o *InlineResponse2003Connector) HasWorkerId() bool {
	if o != nil && o.WorkerId != nil {
		return true
	}

	return false
}

// SetWorkerId gets a reference to the given string and assigns it to the WorkerId field.
func (o *InlineResponse2003Connector) SetWorkerId(v string) {
	o.WorkerId = &v
}

func (o InlineResponse2003Connector) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.WorkerId != nil {
		toSerialize["worker_id"] = o.WorkerId
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2003Connector struct {
	value *InlineResponse2003Connector
	isSet bool
}

func (v NullableInlineResponse2003Connector) Get() *InlineResponse2003Connector {
	return v.value
}

func (v *NullableInlineResponse2003Connector) Set(val *InlineResponse2003Connector) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2003Connector) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2003Connector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2003Connector(val *InlineResponse2003Connector) *NullableInlineResponse2003Connector {
	return &NullableInlineResponse2003Connector{value: val, isSet: true}
}

func (v NullableInlineResponse2003Connector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2003Connector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


