/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse200Tasks struct for InlineResponse200Tasks
type InlineResponse200Tasks struct {
	// ID of the task.
	Id *float32 `json:"id,omitempty"`
	// Current state of the task.
	State *string `json:"state,omitempty"`
	// ID of the worker running the task.
	WorkerId *string `json:"worker_id,omitempty"`
	// Stack trace information if the task has failed.
	Trace *string `json:"trace,omitempty"`
}

// NewInlineResponse200Tasks instantiates a new InlineResponse200Tasks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200Tasks() *InlineResponse200Tasks {
	this := InlineResponse200Tasks{}
	return &this
}

// NewInlineResponse200TasksWithDefaults instantiates a new InlineResponse200Tasks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200TasksWithDefaults() *InlineResponse200Tasks {
	this := InlineResponse200Tasks{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InlineResponse200Tasks) GetId() float32 {
	if o == nil || o.Id == nil {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200Tasks) GetIdOk() (*float32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InlineResponse200Tasks) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *InlineResponse200Tasks) SetId(v float32) {
	o.Id = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *InlineResponse200Tasks) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200Tasks) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *InlineResponse200Tasks) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *InlineResponse200Tasks) SetState(v string) {
	o.State = &v
}

// GetWorkerId returns the WorkerId field value if set, zero value otherwise.
func (o *InlineResponse200Tasks) GetWorkerId() string {
	if o == nil || o.WorkerId == nil {
		var ret string
		return ret
	}
	return *o.WorkerId
}

// GetWorkerIdOk returns a tuple with the WorkerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200Tasks) GetWorkerIdOk() (*string, bool) {
	if o == nil || o.WorkerId == nil {
		return nil, false
	}
	return o.WorkerId, true
}

// HasWorkerId returns a boolean if a field has been set.
func (o *InlineResponse200Tasks) HasWorkerId() bool {
	if o != nil && o.WorkerId != nil {
		return true
	}

	return false
}

// SetWorkerId gets a reference to the given string and assigns it to the WorkerId field.
func (o *InlineResponse200Tasks) SetWorkerId(v string) {
	o.WorkerId = &v
}

// GetTrace returns the Trace field value if set, zero value otherwise.
func (o *InlineResponse200Tasks) GetTrace() string {
	if o == nil || o.Trace == nil {
		var ret string
		return ret
	}
	return *o.Trace
}

// GetTraceOk returns a tuple with the Trace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200Tasks) GetTraceOk() (*string, bool) {
	if o == nil || o.Trace == nil {
		return nil, false
	}
	return o.Trace, true
}

// HasTrace returns a boolean if a field has been set.
func (o *InlineResponse200Tasks) HasTrace() bool {
	if o != nil && o.Trace != nil {
		return true
	}

	return false
}

// SetTrace gets a reference to the given string and assigns it to the Trace field.
func (o *InlineResponse200Tasks) SetTrace(v string) {
	o.Trace = &v
}

func (o InlineResponse200Tasks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.WorkerId != nil {
		toSerialize["worker_id"] = o.WorkerId
	}
	if o.Trace != nil {
		toSerialize["trace"] = o.Trace
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200Tasks struct {
	value *InlineResponse200Tasks
	isSet bool
}

func (v NullableInlineResponse200Tasks) Get() *InlineResponse200Tasks {
	return v.value
}

func (v *NullableInlineResponse200Tasks) Set(val *InlineResponse200Tasks) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200Tasks) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200Tasks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200Tasks(val *InlineResponse200Tasks) *NullableInlineResponse200Tasks {
	return &NullableInlineResponse200Tasks{value: val, isSet: true}
}

func (v NullableInlineResponse200Tasks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200Tasks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


