/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse2001Tasks struct for InlineResponse2001Tasks
type InlineResponse2001Tasks struct {
	// The name of the connector the task belongs to.
	Connector *string `json:"connector,omitempty"`
	// Task ID within the connector.
	Task *float32 `json:"task,omitempty"`
}

// NewInlineResponse2001Tasks instantiates a new InlineResponse2001Tasks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2001Tasks() *InlineResponse2001Tasks {
	this := InlineResponse2001Tasks{}
	return &this
}

// NewInlineResponse2001TasksWithDefaults instantiates a new InlineResponse2001Tasks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2001TasksWithDefaults() *InlineResponse2001Tasks {
	this := InlineResponse2001Tasks{}
	return &this
}

// GetConnector returns the Connector field value if set, zero value otherwise.
func (o *InlineResponse2001Tasks) GetConnector() string {
	if o == nil || o.Connector == nil {
		var ret string
		return ret
	}
	return *o.Connector
}

// GetConnectorOk returns a tuple with the Connector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2001Tasks) GetConnectorOk() (*string, bool) {
	if o == nil || o.Connector == nil {
		return nil, false
	}
	return o.Connector, true
}

// HasConnector returns a boolean if a field has been set.
func (o *InlineResponse2001Tasks) HasConnector() bool {
	if o != nil && o.Connector != nil {
		return true
	}

	return false
}

// SetConnector gets a reference to the given string and assigns it to the Connector field.
func (o *InlineResponse2001Tasks) SetConnector(v string) {
	o.Connector = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *InlineResponse2001Tasks) GetTask() float32 {
	if o == nil || o.Task == nil {
		var ret float32
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2001Tasks) GetTaskOk() (*float32, bool) {
	if o == nil || o.Task == nil {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *InlineResponse2001Tasks) HasTask() bool {
	if o != nil && o.Task != nil {
		return true
	}

	return false
}

// SetTask gets a reference to the given float32 and assigns it to the Task field.
func (o *InlineResponse2001Tasks) SetTask(v float32) {
	o.Task = &v
}

func (o InlineResponse2001Tasks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Connector != nil {
		toSerialize["connector"] = o.Connector
	}
	if o.Task != nil {
		toSerialize["task"] = o.Task
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2001Tasks struct {
	value *InlineResponse2001Tasks
	isSet bool
}

func (v NullableInlineResponse2001Tasks) Get() *InlineResponse2001Tasks {
	return v.value
}

func (v *NullableInlineResponse2001Tasks) Set(val *InlineResponse2001Tasks) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2001Tasks) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2001Tasks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2001Tasks(val *InlineResponse2001Tasks) *NullableInlineResponse2001Tasks {
	return &NullableInlineResponse2001Tasks{value: val, isSet: true}
}

func (v NullableInlineResponse2001Tasks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2001Tasks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


