/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetConnectorTasksResponseTasks struct for GetConnectorTasksResponseTasks
type GetConnectorTasksResponseTasks struct {
	Id *GetConnectorTasksResponseId `json:"id,omitempty"`
	// Configuration of a connector/task/worker. All keys/values should be strings.
	Config map[string]interface{} `json:"config,omitempty"`
}

// NewGetConnectorTasksResponseTasks instantiates a new GetConnectorTasksResponseTasks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConnectorTasksResponseTasks() *GetConnectorTasksResponseTasks {
	this := GetConnectorTasksResponseTasks{}
	return &this
}

// NewGetConnectorTasksResponseTasksWithDefaults instantiates a new GetConnectorTasksResponseTasks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConnectorTasksResponseTasksWithDefaults() *GetConnectorTasksResponseTasks {
	this := GetConnectorTasksResponseTasks{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetConnectorTasksResponseTasks) GetId() GetConnectorTasksResponseId {
	if o == nil || o.Id == nil {
		var ret GetConnectorTasksResponseId
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorTasksResponseTasks) GetIdOk() (*GetConnectorTasksResponseId, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetConnectorTasksResponseTasks) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given GetConnectorTasksResponseId and assigns it to the Id field.
func (o *GetConnectorTasksResponseTasks) SetId(v GetConnectorTasksResponseId) {
	o.Id = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *GetConnectorTasksResponseTasks) GetConfig() map[string]interface{} {
	if o == nil || o.Config == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorTasksResponseTasks) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || o.Config == nil {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *GetConnectorTasksResponseTasks) HasConfig() bool {
	if o != nil && o.Config != nil {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *GetConnectorTasksResponseTasks) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o GetConnectorTasksResponseTasks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Config != nil {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableGetConnectorTasksResponseTasks struct {
	value *GetConnectorTasksResponseTasks
	isSet bool
}

func (v NullableGetConnectorTasksResponseTasks) Get() *GetConnectorTasksResponseTasks {
	return v.value
}

func (v *NullableGetConnectorTasksResponseTasks) Set(val *GetConnectorTasksResponseTasks) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConnectorTasksResponseTasks) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConnectorTasksResponseTasks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConnectorTasksResponseTasks(val *GetConnectorTasksResponseTasks) *NullableGetConnectorTasksResponseTasks {
	return &NullableGetConnectorTasksResponseTasks{value: val, isSet: true}
}

func (v NullableGetConnectorTasksResponseTasks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConnectorTasksResponseTasks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


