/*
Kafka Connect REST API

Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html

API version: 0.1.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetConnectorStatusResponseTasks struct for GetConnectorStatusResponseTasks
type GetConnectorStatusResponseTasks struct {
	// ID of the task.
	Id *float32 `json:"id,omitempty"`
	// Stack trace information if the task has failed.
	Trace *string `json:"trace,omitempty"`
	State *State `json:"state,omitempty"`
	// ID of the worker.
	WorkerId *string `json:"worker_id,omitempty"`
}

// NewGetConnectorStatusResponseTasks instantiates a new GetConnectorStatusResponseTasks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConnectorStatusResponseTasks() *GetConnectorStatusResponseTasks {
	this := GetConnectorStatusResponseTasks{}
	return &this
}

// NewGetConnectorStatusResponseTasksWithDefaults instantiates a new GetConnectorStatusResponseTasks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConnectorStatusResponseTasksWithDefaults() *GetConnectorStatusResponseTasks {
	this := GetConnectorStatusResponseTasks{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetConnectorStatusResponseTasks) GetId() float32 {
	if o == nil || o.Id == nil {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorStatusResponseTasks) GetIdOk() (*float32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetConnectorStatusResponseTasks) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *GetConnectorStatusResponseTasks) SetId(v float32) {
	o.Id = &v
}

// GetTrace returns the Trace field value if set, zero value otherwise.
func (o *GetConnectorStatusResponseTasks) GetTrace() string {
	if o == nil || o.Trace == nil {
		var ret string
		return ret
	}
	return *o.Trace
}

// GetTraceOk returns a tuple with the Trace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorStatusResponseTasks) GetTraceOk() (*string, bool) {
	if o == nil || o.Trace == nil {
		return nil, false
	}
	return o.Trace, true
}

// HasTrace returns a boolean if a field has been set.
func (o *GetConnectorStatusResponseTasks) HasTrace() bool {
	if o != nil && o.Trace != nil {
		return true
	}

	return false
}

// SetTrace gets a reference to the given string and assigns it to the Trace field.
func (o *GetConnectorStatusResponseTasks) SetTrace(v string) {
	o.Trace = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *GetConnectorStatusResponseTasks) GetState() State {
	if o == nil || o.State == nil {
		var ret State
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorStatusResponseTasks) GetStateOk() (*State, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *GetConnectorStatusResponseTasks) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given State and assigns it to the State field.
func (o *GetConnectorStatusResponseTasks) SetState(v State) {
	o.State = &v
}

// GetWorkerId returns the WorkerId field value if set, zero value otherwise.
func (o *GetConnectorStatusResponseTasks) GetWorkerId() string {
	if o == nil || o.WorkerId == nil {
		var ret string
		return ret
	}
	return *o.WorkerId
}

// GetWorkerIdOk returns a tuple with the WorkerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConnectorStatusResponseTasks) GetWorkerIdOk() (*string, bool) {
	if o == nil || o.WorkerId == nil {
		return nil, false
	}
	return o.WorkerId, true
}

// HasWorkerId returns a boolean if a field has been set.
func (o *GetConnectorStatusResponseTasks) HasWorkerId() bool {
	if o != nil && o.WorkerId != nil {
		return true
	}

	return false
}

// SetWorkerId gets a reference to the given string and assigns it to the WorkerId field.
func (o *GetConnectorStatusResponseTasks) SetWorkerId(v string) {
	o.WorkerId = &v
}

func (o GetConnectorStatusResponseTasks) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Trace != nil {
		toSerialize["trace"] = o.Trace
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.WorkerId != nil {
		toSerialize["worker_id"] = o.WorkerId
	}
	return json.Marshal(toSerialize)
}

type NullableGetConnectorStatusResponseTasks struct {
	value *GetConnectorStatusResponseTasks
	isSet bool
}

func (v NullableGetConnectorStatusResponseTasks) Get() *GetConnectorStatusResponseTasks {
	return v.value
}

func (v *NullableGetConnectorStatusResponseTasks) Set(val *GetConnectorStatusResponseTasks) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConnectorStatusResponseTasks) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConnectorStatusResponseTasks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConnectorStatusResponseTasks(val *GetConnectorStatusResponseTasks) *NullableGetConnectorStatusResponseTasks {
	return &NullableGetConnectorStatusResponseTasks{value: val, isSet: true}
}

func (v NullableGetConnectorStatusResponseTasks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConnectorStatusResponseTasks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


