openapi: 3.0.0
info:
  description: Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html
  title: Kafka Connect REST API
  version: 0.1.9
servers:
- url: /
paths:
  /:
    get:
      operationId: getClusterInfo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: OK
      summary: Top-level (root) request that gets the version of the Connect worker
        that serves the REST request, the git commit ID of the source code, and the
        Kafka cluster ID that the worker is connected to.
  /connectors:
    get:
      operationId: listConnectors
      parameters:
      - description: Retrieves additional state/configuration information for each
          of the connectors returned in the API call.
        explode: true
        in: query
        name: expand
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties: true
                description: List of connectors.
                type: object
          description: OK
      summary: Get a list of active connectors.
    post:
      operationId: createConnector
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                name:
                  description: Name of the connector to create
                  type: string
                config:
                  description: Configuration parameters for the connector. All values
                    should be strings.
                  type: object
              type: object
        description: New connector request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: OK
      summary: Create a new connector, returning the current connector info if successful.
        Return 409 (Conflict) if rebalance is in process, or if the connector already
        exists.
  /connectors/{name}:
    get:
      operationId: getConnector
      parameters:
      - description: Name of the created connector.
        explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
          description: OK
      summary: Get information about the connector.
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    inline_response_200_1_tasks:
      example:
        task: 0.8008281904610115
        connector: connector
      properties:
        connector:
          description: The name of the connector the task belongs to.
          type: string
        task:
          description: Task ID within the connector.
          type: number
      type: object
    inline_response_200_1:
      example:
        name: name
        config: '{}'
        tasks:
        - task: 0.8008281904610115
          connector: connector
        - task: 0.8008281904610115
          connector: connector
      properties:
        name:
          description: Name of the created connector
          type: string
        config:
          description: Configuration parameters for the connector.
          type: object
        tasks:
          description: Lits of active tasks generated by the connector.
          items:
            $ref: '#/components/schemas/inline_response_200_1_tasks'
          type: array
      type: object
    inline_response_200:
      example:
        kafka_cluster_id: kafka_cluster_id
        commit: commit
        version: version
      properties:
        version:
          description: Connect worker version.
          type: string
        commit:
          description: Git commit ID.
          type: string
        kafka_cluster_id:
          description: Kafka cluster ID.
          type: string
      type: object
    inline_object:
      properties:
        name:
          description: Name of the connector to create
          type: string
        config:
          description: Configuration parameters for the connector. All values should
            be strings.
          type: object
      type: object
    inline_response_200_2:
      example:
        name: name
        config: '{}'
        tasks:
        - task: 0.8008281904610115
          connector: connector
        - task: 0.8008281904610115
          connector: connector
      properties:
        name:
          description: Name of the created connector.
          type: string
        config:
          description: Configuration parameters for the connector.
          type: object
        tasks:
          description: List of active tasks generated by the connector.
          items:
            $ref: '#/components/schemas/inline_response_200_1_tasks'
          type: array
      type: object
